import { Ubuntu } from "next/font/google";
import "./globals.css";
import FooterBox from "@/app/components/(bjorn)/FooterBox";

const ubuntuSans = Ubuntu({
  variable: "--font-ubuntu-sans",
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Night Club",
  description: "Generated by Skimmelsvampene",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${ubuntuSans.variable} antialiased`}
      >
        {children}
        <FooterBox />
      </body>
    </html>
  );
}